### ISSUE TITLE
Sequentially reading LMDB

### ISSUE THREAD

**Issue by achalddave** [jnwatson/py-lmdb#115]
Maybe I'm not using this the right way, but it seems that sequentially reading an LMDB using a single transaction causes memory usage to constantly grow.

Here's a small script that demonstrates this:

``` python
import lmdb

DB_PATH="./database.lmdb"

num_entries = 0
with lmdb.open(DB_PATH, map_size=500e9).begin(
        write=False).cursor() as cursor:
    cursor_iterator = cursor.iternext()
    for _, _ in cursor_iterator:
        num_entries += 1
print num_entries
```

(I'm aware that it's possible to count the number of entries by using `stat()` - this is just an easy way to show the problem.)

Is this expected? I assume breaking up the transactions would solve this issue, but that makes the code uglier.

Edit: This is an issue even if the cursor_iterator is created using

``` python
cursor_iterator = cursor.iternext(values=False)
```

**Comment by dw** [comment]
Hello, please review http://lmdb.readthedocs.io/en/release/#memory-usage and ensure you are measuring correctly. Most memory diagnostic tools provide a useless metric when a process has large clean memory maps loaded

**Comment by achalddave** [comment]
Argh, I should have looked at that first. Thanks. Perhaps this is a naive question, but does this mean that if I were to try to iterate over an LMDB that is larger than my RAM, the OS will handle reclaiming the memory and not crash?

At this point, this is a usage question, but is there a way to decrease the Clean memory usage, or set a limit on how much of the LMDB is cached? One issue we're running into is using LMDB with a resource management system, SLURM, which (I believe) relies on cgroups to kill jobs that exceed a specified memory limit. Unfortunately, it seems the memory limits include Clean memory, so we can't use Slurm to schedule jobs that read LMDBs - I figured I'd check if this is a problem people have run into before, or if there's a better forum to ask this question.

**Comment by dw** [comment]
That's exactly what should happen. The exact semantics on Linux are supposedly "mostly LRU replacement policy", however that policy is global to the kernel, not to your process. For example, the kernel will consider other unused read-only mappings as candidates for reclaim often before it will consider candidates from your own address spaces.

Larger-than-RAM LMDB can be quite annoying to get right due to this, so let me know if you have any problems, there are quite a few kernel tunables that can help

**Comment by dw** [comment]
Ah I completely missed the second part of your reply. Will follow up shortly

**Comment by dw** [comment]
Variants of this pop up often enough that I'm going to keep this open and use it as a documentation bug at least.

**Comment by achalddave** [comment]
Thanks, that's really helpful! LRU seems slightly troublesome, as with the issue here (where the OS will start claiming other process' pages if I were to read through an LMDB sequentially) http://www.openldap.org/lists/openldap-technical/201503/msg00077.html

I think for now breaking the read into chunks works, since this forces pages to be flushed. Any other suggestions would be appreciated!

**Comment by jnwatson** [comment]
I think this behavior is now sufficiently documented.
