### ISSUE TITLE
Problem with large DBs (Memory Limit Error)

### ISSUE THREAD

**Issue by arashno** [jnwatson/py-lmdb#119]
Hi all,
I have a large lmdb, about 800K images.
I want to just read the entries one by one.
My code is very simple and looks like this:

```
with env.begin() as txn:
    cursor = txn.cursor()
    for key, value in cursor:
        print(key)
```

But after reading about 70000 entries it runs out of memory (~10GB).
I have no idea why.
I tried to do like below but it didn't work.

```
for r in range(0,env.stat()['entries']):
    if r%10000==0:
        if r!=0:
            txn.commit()
            cur.close()
        txn=env.begin()
        cur = txn.cursor()
        print("Change Change Change "+ str(r))
        sys.stdout.flush()
        if r==0:
            cur.first()
        else:
            cur.set_range(key)
            cur.next()
    key, value = cur.item()
```

any suggestion?

**Comment by dimaqq** [comment]
I think what happens is that `value` is copied.
(I'm assuming values are images, large)

If that's the case, try the `buffer` interface instead.
(pypi/lmdb offers such interface, I dunno about py-lmdb)

**Comment by ifduyue** [comment]
> (pypi/lmdb offers such interface, I dunno about py-lmdb)

They are the same.
