### ISSUE TITLE
overwrite=True flag documentation

### ISSUE THREAD

**Issue by nilp0inter** [jnwatson/py-lmdb#147]
Hi,

Is very difficult for a newcomer to understand that overwrite must be True in cursor.put for the database to add duplicates when dupsort is also True.

A few words in the docs may help a lot.

Thank you for the great work!

**Comment by dw** [comment]
This is news to me :)  It sounds more like a bug. Will take a look tonight. Thanks for reporting

**Comment by jnwatson** [comment]
Thank you for your observation. I've added a note to the documentation of put.
