### ISSUE TITLE
subdatabases with open_db, possible to distinguish key->value from key->subdb?

### ISSUE THREAD

**Issue by grez72** [jnwatson/py-lmdb#184]
Linux Ubuntu 16.04, lmdb version '0.94' (installed with: sudo pip install lmdb)

Not sure if this is the right place to ask, but I'm using py-lmdb to create a database within a folder, and then using the "open_db" method to add subdatabases. Everything works well, but I'm also storing metadata in key->value pairs of the main database. Is it possible to distinguish between these key->value metadata pairs, and the key->subdatabase pairs? 

e.g., 
```
with lmdb.open('test', readonly=True) as env:
    with env.begin() as txn:
        cursor = txn.cursor()
        for key, value in cursor:
            # How can I determine whether current value is a sub-database?
            try:
                print(json.loads(value))
            except Exception as e:
                print(e)
```
### Here's how I created the test database (test) and subdb (b'data001)

```
import lmdb
import json

env = lmdb.open('test', max_dbs=100, readonly=False)
subdb = env.open_db(b'data001')

try:
    with env.begin(write=True) as txn:
        txn.put(b'metadata', json.dumps('somedata').encode())
        
    with env.begin(write=True, db=subdb) as txn:
        datum = {
            "data": [7, 8, 9],
            "label": 0
        }
        txn.put(b'subdb001', json.dumps(datum).encode())
        
except Exception as e:
    print(e)
finally:
    env.close() 
```

**Comment by dw** [comment]
Hi, sorry for the late reply. Upstream's advice is that you do not mix data and non-data keys in the main database. Either create an environment with zero sub-databases and keep all your data in the main database, or keep your main database 'empty' and populate only sub-databases.
