### ISSUE TITLE
MDB_CORRUPTED: Located page was wrong type

### ISSUE THREAD

**Issue by PeteJanda** [jnwatson/py-lmdb#185]
Does anyone know what this return code means exactly?  Neither LMDB's publisher nor anyone else I've come across explains it, so I cannot fix the underlying issue.  Thanks.

**Comment by dw** [comment]
Hi Pete,

Under what circumstances is it appearing? Please let us know:

- Host OS
- Python binding version / is it linked to bundled LMDB or system LMDB
- Type of filesystem the failing DB resides on
- Is the problem repeatable?
- Flags used to open the environment
- Are multiple processes accessing the DB?
- What operation is being performed when the error occurs?

Thanks,

**Comment by PeteJanda** [comment]
Circumstances (high-level) = Fresh, successful installation of Caffe deep learning framework, which comes with code called "create_MNIST" that loads 60k 28x28 pixel images into LMDB for later consumption by Caffe. 

Host OS = Ubuntu 16.04
File System = EXT4
Multiple Processes = No
Repeatable  = Yes... consistently
Flags for Env Open = 0
Operation Triggering the Error = Put

But the more I poke into this, the more I believe this error / return code isn't Python binding-specific... it seems like something with LMDB itself.  The only LMDB "page" concept I'm aware of is in the context of OS-defined memory page sizes, but I haven't the slightest clue what a "wrong type" of memory page could signify.

**Comment by dw** [comment]
The error itself means LMDB found a leaf page where an internal page was expected (in btree parlance), but it doesn't explain why that's happening :)

Can you share the output of e.g. "pip freeze", and a short reproduction involving the function so we have something to go on.

It may be possible that changes elsewhere in CAFFE (which AFAIK is relatively large) have introduced a bug that is affecting LMDB, for example, by corrupting data in a writeable memory map.

Are you using the regular system Python?

What command did you use to install CAFFE, just 'pip install'? 

Thanks :)

**Comment by dw** [comment]
Having just checked CAFFE, it doesn't seem to use py-lmdb at all :)  You should chat to CAFFE developers about this, and they should probably talk to upstream directly.
