### ISSUE TITLE
Confusion about dupsort database and put

### ISSUE THREAD

**Issue by coleifer** [jnwatson/py-lmdb#189]
The docs for the `put()` parameter `dupdata` lead me to believe that, even if I have `dupsort=True` for my database, I can specify `dupdata=False` and the value will be replaced:

> dupdata:
> If True and database was opened with dupsort=True, add pair as a duplicate if the given key already exists. Otherwise overwrite any existing matching key.

For example, in the following scenario I would expect to see "v1-6" since I am specifying `dupdata=False`, however the db prints "v1-5" (since v1-6 is stored as a duplicate):

```python
print(lmdb.__version__)

env = lmdb.open('/tmp/lmdbtest-1', max_dbs=10)
db = env.open_db(b'db0', dupsort=True)

txn = env.begin(db, write=True)
txn.put('k1', 'v1-5')
txn.put('k1', 'v1-6', dupdata=False, overwrite=True)
print(txn.get('k1'))
txn.abort()
env.close()

# 0.94
# v1-5
```

The docs make it sound like "if db has dupsort" **and** "dupdata=True", then we'll store a duplicate -- otherwise it acts like a replace.

But it does not appear to be correct. In fact, the dupdata parameter seems to have no effect either way (?).

### Affected Operating Systems

* Linux

### Affected py-lmdb Version

    0.94

### py-lmdb Installation Method

built from source

### Using bundled or distribution-provided LMDB library?

Bundled

### Distribution name and LMDB library version

0, 9, 22

**Comment by coleifer** [comment]
Perhaps I'm confusing `put` (with `dupdata=False`) with `replace`?

**Comment by jnwatson** [comment]
py-lmdb inherited this confusion from upstream. On a `dupsort` database, `overwrite` does nothing, and `dupdata` only changes the return value from `put` if the data was already there.
`replace` works because it deletes the entry then puts it as two separate calls into the c lmdb library.
