### ISSUE TITLE
MANIFEST.in probably including too much

### ISSUE THREAD

**Issue by asodeur** [jnwatson/py-lmdb#190]
Due to the `graft .` command in `MANIFEST.in` the sdist is containing some unusual things, like `.git`, `.gitignore` etc.

Not sure this is intentional but especially the `.git` directory is causing issues with build tools on Windows as some of the files are read-only and prevent removal of temp dirs created during install.

**Comment by dw** [comment]
This looks like a change in modern distutils, MANIFEST.in hasn't changed in a long time, and there was no .git directory present in 0.89. I'll see about getting a new release out shortly. Thanks for reporting this

**Comment by dw** [comment]
Seems recent releases have dropped Windows binaries too :(  I should hopefully have time to look at this before Monday. Sorry for the inconvenience
