### ISSUE TITLE
Mac OS lmdb.DiskError No space left on device, but there are actually many in os

### ISSUE THREAD

**Issue by zengjice** [jnwatson/py-lmdb#200]
Hi,

When I ran the lmdb program many times, I will report this problem. Checked the operating system and found that there is still a lot of disk space. After restarting the computer, it can be used again. This incident is very troublesome. I have to restart my computer when I appear. I hope you can help me. Thanks.

### Affected Operating Systems

* MAC OS Mojave 10.14.4

### Affected py-lmdb Version

0.9.4

### py-lmdb Installation Method

sudo pip install lmdb

### Using bundled or distribution-provided LMDB library?

Not sure

### Distribution name and LMDB library version

(0, 9, 22)

### Machine "free -m" output

MAC OS no free command. I use top command and sorted by memory:

![image](https://user-images.githubusercontent.com/5196427/60763060-1b504380-a09f-11e9-8cb3-f3905ab2824c.png)

There are doubts here, you can see from the PhysMem use 29G memory, but from the following sort of order, it seems that there should be no more than 29G, then where is the rest of the memory, used to do the cache?

### Other important machine info

no

### Describe Your Problem

At the top.

### Errors/exceptions Encountered

```
    return lmdb.open(path, create=True, max_dbs=1, max_readers=1024, lock=write, sync=True, map_size=10_737_418_240)
lmdb.DiskError: 20190707_094959_560049_1/880e7e68-a059-11e9-9e2e-acde48001122/0: No space left on device
```

### Describe What You Expected To Happen

I expected the transaction to commit successfully.

### Describe What Happened Instead

not work

**Comment by jnwatson** [comment]
'lock=write" looks odd, but that shouldn't be the problem.

You don't happen to be running a python built for 32-bits are you? What is the output of `python -c 'import sys; print(sys.implementation)'?

**Comment by zengjice** [comment]
namespace(_multiarch='darwin', cache_tag='cpython-36', hexversion=50727152, name='cpython', version=sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0))

thanks.

**Comment by jnwatson** [comment]
I'm sorry, that didn't give me the info I needed. What is the output of 
`python -c 'import sys;print("%x" % sys.maxsize)'`

**Comment by zengjice** [comment]
7fffffffffffffff

thanks.

**Comment by zengjice** [comment]
![image](https://user-images.githubusercontent.com/5196427/60852857-18cf2480-a22c-11e9-8127-1310edcfabf8.png)
thanks.

**Comment by jnwatson** [comment]
Ok. I'm still confused. What about `df 20190707_094959_560049_1/880e7e68-a059-11e9-9e2e-acde48001122/0`

**Comment by zengjice** [comment]
![image](https://user-images.githubusercontent.com/5196427/60889211-2071e600-a28b-11e9-8b50-bcb326f90889.png)

**Comment by jnwatson** [comment]
This looks like an upstream problem (lmdb). lmdb reports ENOSPC when a value from pwrite returns an unexpected value. I don't have a Mac available to test with. If you could run your program again with dtruss, looking for ptrace calls, that would give me an idea what's going on.
