### ISSUE TITLE
Spare read transactions leakage (cpython)

### ISSUE THREAD

**Issue by zougloub** [jnwatson/py-lmdb#205]
In a long-living program I've noticed the number of read transactions to be increasing until the limit is busted.

There seems to be an issue in the cpython wrapper (tested on 0.96), related to spare read transactions: disabling the spare read transactions mechanism, or forcing use of the CFFI wrapper both bypass the problem.

```diff
Hack to bypass logic of space transactions by forcing initialization of max_spare_txns to -1 and checking for it when about to create a spare transaction.
--- a/lmdb/cpython.c
+++ b/lmdb/cpython.c
@@ -859 +891 @@ make_trans(EnvObject *env, DbObject *db, TransObject *parent, int write, int buf
-    if((!write) && env->spare_txns) {
+    if((!write) && env->max_spare_txns >= 0 && env->spare_txns) {
@@ -1245,0 +1278 @@ env_new(PyTypeObject *type, PyObject *args, PyObject *kwds)
+    self->max_spare_txns = -1;
```

There's some smell in the use of `_Py_NewReference()`, not `Py_INCREF()`, which is unmatched.

**Comment by jnwatson** [comment]
That could also be application-side problem. Do you have a repeatable test case?

**Comment by zougloub** [comment]
I don't yet have a minimal & shareable repeatable test case (trying...).
My problem can be seen in a "main loop" running in a thread, and I can see with the reader monitoring of `python -m lmdb` that with time, the number of readers increases.

How could there be an application-side problem? With a handful of threads running, what else than deep recursive code could get over 126 concurrent readers?

**Comment by jnwatson** [comment]
Leaving transactions open can cause this problem. The easiest way to
prevent this is to always open a transaction with a context manager.

Nic

**Comment by zougloub** [comment]
My bad: I had inserted somewhere a functools.lru_cache in a db getter, and somehow in order to avoid creating nested transactions the transaction was passed as a parameter to the lru_cached function.
