### ISSUE TITLE
Failed to install via pip3, with VC2019

### ISSUE THREAD

**Issue by quark2019** [jnwatson/py-lmdb#206]
--------------
vc2019 has been installed, why lmdb require to install vc14??
Is there a way to wrok around this issue? (now is year 2019, it's too bad to require vc14)

I tried to install 'Visual C++ Redistributable for Visual Studio 2015' that download from Microsoft homepage,  but it failed to install, because vc2019 has been installed.

waiting for a reply, much thanks!
--------------------------------------------------
env: 
OS: win10, x64
installed: python3.7, visual studio 2019 
--------------------------------------------------
$ pip install lmdb
Collecting lmdb
  Using cached https://files.pythonhosted.org/packages/86/5c/6ad690daeaa00b328606bf2fa435244a11cc2dd9aedac6ef4d2ef2a21f6e/lmdb-0.96.tar.gz
Building wheels for collected packages: lmdb
...
...
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for lmdb

**Comment by jnwatson** [comment]
I'd be happy to entertain a PR.

**Comment by August-Ghost** [comment]
You have to install MSBuildTools(Sorry for my Chinese version page)：
![image](https://user-images.githubusercontent.com/15943189/63675410-578c5e80-c81b-11e9-8675-f06a67b8b718.png)
and select C++ build tools(Or something like that)：
![image](https://user-images.githubusercontent.com/15943189/63675554-a934e900-c81b-11e9-8af3-cb149cbe15c3.png)
