### ISSUE TITLE
Binary wheels

### ISSUE THREAD

**Issue by ofek** [jnwatson/py-lmdb#209]
Can we please ship binary wheels once again? Hopefully for all platforms, but even just Windows would be a good start. See:

https://pypi.org/project/lmdb/0.93/#files
https://github.com/jnwatson/py-lmdb/issues/158

@jnwatson Thank you very much for picking up this excellent project!

**Comment by jnwatson** [comment]
I will look into it.

**Comment by jnwatson** [comment]
I have uploaded all the Windows binaries.

**Comment by ofek** [comment]
Thanks! Will they also be a standard part of future releases?

**Comment by jnwatson** [comment]
Yes
