### ISSUE TITLE
Solaris needs ```#include "python.h"``` as soon as possible

### ISSUE THREAD

**Issue by jcea** [jnwatson/py-lmdb#213]
### Affected Operating Systems

* Solaris family

### Affected py-lmdb Version

Releases after Jan 22, 2019.

### py-lmdb Installation Method

sudo pip install lmdb

### Using bundled or distribution-provided LMDB library?

Bundled and distribution-provided.

### Describe Your Problem

After PR #194 was integrated, LMDB doesn't work on Solaris based systems.

Full triage and details: https://github.com/joyent/pkgsrc/issues/207

TL;DR: After PR #194, code uses ```errno```. In Solaris, ```errno``` implementation depends of ```_REENTRANT``` symbol defined of not. In distribution-based python, ```_REENTRANT``` is defined in ```python.h```, but in current LMDB code ```#include "python.h"``` is done AFTER ```#include <errno.h>```, too late for it to have the right effect.

Tha patch is trivial: do ```#include <errno.h>``` later or, better, do ```#include "python.h"``` because could be some other side-effects that we want to enable ASAP.

Pull Request in a few minutes.

### Errors/exceptions Encountered

LMDB fails to open an old database because ```errno``` doesn't recognize "file exists" error on Solaris.

**Comment by jcea** [comment]
PR #214

**Comment by jnwatson** [comment]
Thank you. PR accepted.
