### ISSUE TITLE
MDB_CORRUPTED error (Located page was wrong type) when trying to build database in WSL 

### ISSUE THREAD

**Issue by AlessandroVol23** [jnwatson/py-lmdb#215]
### Affected Operating Systems

* WSL (Windows Subsystem for Linux) Ubuntu 18.04 LTS

### Affected py-lmdb Version

 0.94 and 0.95

### py-lmdb Installation Method

```shell
conda create -n delft_cpu_95 python=3.5
conda activate delft_cpu_95
pip install --upgrade pip
pip install -r requirements.txt
```

requirements.txt:
```
keras==2.2.4
numpy==1.16.1
pandas==0.22.0
bleach>=2.1.0
regex==2018.2.21
scikit-learn==0.19.1
tqdm==4.21
tensorflow==1.12.0
gensim==3.4.0
langdetect==1.0.7
textblob==0.15.1
h5py==2.7.1
unidecode==1.0.22
pydot==1.2.4
// Tried it with 0.94 and 0.95
lmdb==0.95
keras-bert==0.39.0
```

### Using bundled or distribution-provided LMDB library?

Not sure about that, sorry. Please see here https://github.com/kermitt2/delft

### Distribution name and LMDB library version

```PY
print(lmdb.version())
(0, 9, 22)
```

### Machine "free -m" output

```
              total        used        free      shared  buff/cache   available
Mem:          32659       27084        5351          17         223        5444
Swap:         30446       10902       19544
```

### Other important machine info

Windows subsystem for linux used! Maybe problem with WSL https://github.com/jnwatson/py-lmdb/issues/185

### Describe Your Problem

Hi,

I get following error when trying to save word embeddings in lmdb. I try using this repository: 
https://github.com/kermitt2/delft and try to execute 
```shell
python toxicCommentClassifier.py train
```
### Errors/exceptions Encountered

```python
Traceback (most recent call last):
  File "toxicCommentClassifier.py", line 103, in <module>
    train(embeddings_name=embeddings_name, fold_count=args.fold_count, architecture=architecture, use_ELMo=use_ELMo, use_BERT=use_BERT)
  File "toxicCommentClassifier.py", line 27, in train
    embeddings_name=embeddings_name, use_ELMo=use_ELMo, use_BERT=use_BERT, batch_size=batch_size, maxlen=maxlen)
  File "/d/repo/delft/delft/textClassification/wrapper.py", line 65, in __init__
    self.embeddings = Embeddings(embeddings_name, use_ELMo=use_ELMo, use_BERT=use_BERT)
  File "/d/repo/delft/delft/utilities/Embeddings.py", line 65, in __init__
    self.make_embeddings_simple(name)
  File "/d/repo/delft/delft/utilities/Embeddings.py", line 296, in make_embeddings_simple
    self.make_embeddings_lmdb(name, hasHeader)
  File "/d/repo/delft/delft/utilities/Embeddings.py", line 218, in make_embeddings_lmdb
    txn.put(word.encode(encoding='UTF-8'), _serialize_pickle(vector))
lmdb.CorruptedError: mdb_put: MDB_CORRUPTED: Located page was wrong type
``` 

### Describe What You Expected To Happen

- Save embeddings in lmdb database
### Describe What Happened Instead

Python process crashed with error message above. 

I'll try it in a virtual machine with Ubuntu to figure out the problem. 
I tried to delete the db folder which didn't help. 

Thanks for your help :-)

**Comment by AlessandroVol23** [comment]
So it worked with a Hyper-V ubuntu VM. I am pretty sure it has something to do with WSL.

**Comment by jnwatson** [comment]
It looks like there are mmap issues with WSL 1: https://github.com/Microsoft/WSL/issues/902

This is really up to Microsoft to fix. As an alternative, lmdb for Windows works fine. You could also try WSL 2. It runs a whole Linux kernel, so there should be an issues with system call emulation.
