### ISSUE TITLE
rewrite command does not encode database name

### ISSUE THREAD

**Issue by jbosboom** [jnwatson/py-lmdb#219]
### Affected Operating Systems

* Linux (nothing else tested)

### Affected py-lmdb Version

    0.95

### py-lmdb Installation Method

    sudo pip install lmdb

### Using bundled or distribution-provided LMDB library?

Bundled, I think.  I have Arch Linux's lmdb 0.9.24-1 installed but `lmdb.version()` reports `(0, 9, 22)`.

### Machine "free -m" output

Unlikely to be relevant to this issue.

```
              total        used        free      shared  buff/cache   available
Mem:          125Gi       706Mi       1.1Gi       1.0Mi       124Gi       123Gi
Swap:            0B          0B          0B
```

### Problem

The `rewrite` command does not encode database names under Python 3.  Other commands are probably affected but I didn't try them.

    python -m lmdb -e /data/raid/source.mdb/ -E /data/raid/target.mdb/ rewrite test_subdatabase

gives

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/lmdb/__main__.py", line 24, in <module>
    lmdb.tool.main()
  File "/usr/lib/python3.7/site-packages/lmdb/tool.py", line 627, in main
    func(opts, args[1:])
  File "/usr/lib/python3.7/site-packages/lmdb/tool.py", line 512, in cmd_rewrite
    src_db = ENV.open_db(name)
TypeError: Won't implicitly convert Unicode to bytes; use .encode()
```

but the same command with `python2` works.

**Comment by jnwatson** [comment]
repro'd on 0.98. ty
