### ISSUE TITLE
rewrite command does not create new databases with flags, probably because `mdb_dbi_flags` is not in API

### ISSUE THREAD

**Issue by jbosboom** [jnwatson/py-lmdb#220]
### Affected Operating Systems

* Linux (nothing else tested)

### Affected py-lmdb Version

    0.95

### py-lmdb Installation Method

    sudo pip install lmdb

### Using bundled or distribution-provided LMDB library?

Bundled, I think.  I have Arch Linux's lmdb 0.9.24-1 installed but `lmdb.version()` reports `(0, 9, 22)`.

### Machine "free -m" output

Unlikely to be relevant to this issue.

```
              total        used        free      shared  buff/cache   available
Mem:          125Gi       706Mi       1.1Gi       1.0Mi       124Gi       123Gi
Swap:            0B          0B          0B
```

### Problem

The `rewrite` command creates databases in the target environment without setting any database flags.  I expect the flags from the source database to be used.  In particular, this means `rewrite` can't append-copy databases with `MDB_REVERSEKEY` or `MDB_INTEGERKEY` (on little-endian machines) because the sort orders differ between the source and target database.

`mdb_dbi_flags` does not seem to be exposed in the Python API.  Even if `python -m lmdb` is not a development priority for you, exposing this function would let me implement the relevant functionality in my own scripts.

**Comment by jnwatson** [comment]
ty for the bug report. You are correct in that the flags aren't being used to create the new databases. That's a bug.

On the bright side, the result of mdb_dbi_flags for a database is available via the `flags` method on the database object itself. See https://lmdb.readthedocs.io/en/release/#lmdb.Environment.flags

**Comment by jbosboom** [comment]
> On the bright side, the result of mdb_dbi_flags for a database is available via the `flags` method on the database object itself. See https://lmdb.readthedocs.io/en/release/#lmdb.Environment.flags

I haven't tried it, but based on the documentation ("Return a dict describing Environment constructor flags used to instantiate this environment.") I think that's `mdb_env_get_flags`, not `mdb_dbi_flags`.  As further evidence, that's a method on the Environment, and it doesn't take a database handle argument, so there's no way to tell which database's flags you're getting.

**Comment by jnwatson** [comment]
You're right. I sent you a link to the wrong method. It looks like the flags method on the database is not documented. It does work though.

`[nav] In [13]: txn = env.begin(write=True, db=db)

[nav] In [14]: db.flags(txn)
Out[14]:
{'reverse_key': False,
 'dupsort': False,
 'integerkey': False,
 'integerdup': False,
 'dupfixed': False}
`
