### ISSUE TITLE
Update to new upstream lmdb version

### ISSUE THREAD

**Issue by kawing-chiu** [jnwatson/py-lmdb#229]
I noticed that the upstream lmdb version is currently at [0.9.24](https://github.com/LMDB/lmdb/releases), released at Jul 20, 2019. Maybe py-lmdb can be updated to use the newer version?

**Comment by jnwatson** [comment]
I was expecting a new upstream release any day now...

**Comment by AskAlexSharov** [comment]
FYI: newer lmdb bumped .lock file version. It's not-backward-compatible change (will get MDB_VERSION_MISMATCH if see old lock file).

**Comment by jnwatson** [comment]
Watch patch did that happen in? I don't see it.

**Comment by AskAlexSharov** [comment]
Ouch, probably I was not clear enough. 

It doesn't happening now, but it will - if update lmdb sources.

- lmdb version 0.9.24 (which used in py-lmdb) has lock version 1: https://github.com/jnwatson/py-lmdb/blob/master/lib/mdb.c#L539
- Master branch of lmdb has lock version 2: https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/mdb.c#L636

**Comment by jnwatson** [comment]
That's interesting. The lock change was made in https://github.com/LMDB/lmdb/commit/58ba039b8f30733ad9456cb3a31f9c459e6e0ffe, which is more than 3 years ago.

They haven't released off mdb.master in a long time now.

Thank you for the information.

**Comment by kawing-chiu** [comment]
Here's another project which claims to be an improved version of lmdb: [libmdbx](https://github.com/erthink/libmdbx)

**Comment by jnwatson** [comment]
I briefly communicated with the author of that project about Python bindings for that. It looks quite interesting, though I am concern that most of the future effort is going to land into his successor closed-source DB.

**Comment by kawing-chiu** [comment]
From the readme it says that the new DB will be named 'MithrilDB' and released under Apache 2.0 license. However, from the commit logs, it seems that libmdbx per se is still under heavry development.

**Comment by AskAlexSharov** [comment]
MithrilDB is about SQL on top of mdbx. Mdbx changed not much API (changed mdb_ prefix and a bit new features). 

We still not tested mdbx because it has not python bindings (which is valuable feature for us).

**Comment by jnwatson** [comment]
I see. This project would be a good model, though it does have some legacy cruft to it. I've been waiting for [HPy](https://github.com/pyhandle/hpy) to mature to start another serious C module effort. The fact that this project has to maintain two parallel implementations is problematic, to say the least.
