### ISSUE TITLE
Interface to force environment to pre-allocation map_size

### ISSUE THREAD

**Issue by pvmilk** [jnwatson/py-lmdb#233]
### Affected Operating Systems
* [Other] Linux (on the cloud)

### Affected py-lmdb Version

    e.g. lmdb==0.98

### py-lmdb Installation Method

    sudo pip install lmdb (managed by conda)

### Using bundled or distribution-provided LMDB library?

Bundled

### Machine "free -m" output

n/a

### Other important machine info

Running in the container. 
Using a mount storage [IBM Cloud Object Storage](https://en.wikipedia.org/wiki/IBM_Cloud_Object_Storage). I am not sure whether it support sparse file.

### Describe Your Problem
I have the issue that lmdb size cannot be extended in the filesystem. 

I would like to know whether there is a flag that allow the lmdb file to pre-allocate the file with map_size during initialization.
I have tried `write_map=True`, but then there is another error as describe below. 

### Errors/exceptions Encountered

The lmdb file can be created (data.mdb, lock.mdb).
A few data can be put, but then the throw the following error after a certain amount of data
```
lmdb.Error: mdb_txn_commit: Input/output error
```
I believed that the filesystem might not allow the size of the lmdb file to be extended. The size of data.mdb always stopped at 52M, even though I tried to populated different dataset.

----------------
In addition, I have also tried `write_map=True`. The lmdb file can be created (data.mdb, lock.mdb), but none of the content can be write to the file.  The error was simply just core dumped.

### Describe What You Expected To Happen

The same program is tested and run on linux file system, and it works fine (both with write_map=[True|False]).

**Comment by jnwatson** [comment]
This looks like whatever filesystem you're running on isn't implemented correctly or is running into some system-dependent limitation. On non-sparse filesystems, lmdb automatically preallocates the whole file (in fact it happens automatically on the first write after a seek). LMDB doesn't strictly require sparse file systems as it works on Mac and Windows. You might try running `strace` on your test code to see what system call is failing (probably a write) and the precise error code that it is returning.

**Comment by pvmilk** [comment]
Thank you very much for your reply. 

It seems the automatic pre-allocation is not done in this case (only 52MB is allocated). Let me try to `strace` as you mentioned.

**Comment by pvmilk** [comment]
@jnwatson I did a small experiment. Do you have any opinion on this?

### Main Experiment

I wrote a small snippet and run it in the system. 
The code is in the attachment([write_lmdb.txt](https://github.com/jnwatson/py-lmdb/files/4726006/write_lmdb.txt)), but I extracted on the necessary part here for explanation. 


```
    lmdb_writer = lmdb.open(lmdb_path, map_size=map_size, max_readers=128, readonly=False, lock=True)

    print('1st write')
    txn = lmdb_writer.begin(write=True)
    for idx in range(0, args.record_num):
        if idx % 10 == 0:
            print(idx)
        w_success = txn.put(('idx-{:08d}'.format(idx)).encode('ascii'), pickle.dumps(dummy_data), dupdata=False, overwrite=False)
        assert w_success
    txn.commit()

    print('2nd write')
    for idx in range(0, args.record_num):
        if idx % 10 == 0:
            print(idx)
        txn = lmdb_writer.begin(write=True)
        w_success = txn.put(('idx_alt-{:08d}'.format(idx)).encode('ascii'), pickle.dumps(dummy_data), dupdata=False, overwrite=False)
        txn.commit()
        assert w_success

    lmdb_writer.close()

```
It seems that the error always occurs in the `2nd write` block during commit, between idx = [0, 10).
`lmdb.Error: mdb_txn_commit: Input/output error`
strace can be found in the attachment ([trace.txt](https://github.com/jnwatson/py-lmdb/files/4726032/trace.txt)).

### Additional Experiments
Originally, args.record_num = 100, and the size of data.mdb is 130M
- I suspected whether it is the allocation space limit, so I increase args.record_num = 300, but still the error still occurs in the `2nd write`, between idx = [0, 10).
  - size of data.mdb is 386M
- I suspected whether I might have close the transaction too fast, so I add sleep before commit. I tested two sleep durations (50ms, 500ms), but both produce the same error during `2nd write`, between idx = [0, 10).
  - size of data.mdb is 130M 
- I tried to execute `2nd write` block before `1st write` block. The same error appears in the '2nd write' block as usual, but the idx =[40, 50]. It means that it did successfully write/commit for a few key/value. 
  - size of data.mdb is 54M

### Question

My original code is actually very similar to `2nd write` block (+multi threading). 
Do you have any suggested to improve this, or the only way to make it work is to wrote the code as `1st write` block and use only 1 thread?

**Comment by jnwatson** [comment]
It is hard to say what future filesystem issues you might run into in your very exotic situation.

One idea: try initializing your database files on a regular filesystem, then copy them to your target filesystem. In that way, all the preallocation should occur.

**Comment by pvmilk** [comment]
@jnwatson Thank you very much for a reply. 

Actually that was a very good idea.
Since I only use the database files for caching, I don't really need to copy them even.
