### ISSUE TITLE
dupsort argument doesn't seem to be working

### ISSUE THREAD

**Issue by 25thbamofthetower** [jnwatson/py-lmdb#234]
### Affected Operating Systems
Linux

### Affected py-lmdb Version
0.98

### py-lmdb Installation Method
pipenv install lmdb

### Other important machine info
Running in docker container

### Describe Your Problem

The argument `dupsort` to `env.open_db()` doesn't seem to work as expected in allowing duplicate keys, unless I'm reading the documentation wrong then please correct me.

```python
env = lmdb.open(path.join(directory, 'lmdb'), map_size=map_size)
db = env.open_db(dupsort=True)

with env.begin(db=db, write=True) as transaction:
    print(db.flags(transaction))
    transaction.put(b'a', b'test1')
    transaction.put(b'a', b'test2')
    transaction.put(b'a', b'test3')
```
Then when I check the values, I only get the last input value `test3`. I used both `iternext()` and `iternext_dup()`.

```python
with env.begin(db=db) as transaction:
    cursor = transaction.cursor()
    cursor.set_key(b'a')
    for key, value in cursor.iternext_dup(True, True):
        print(key, value)
```
And also

```python
with env.begin(db=db) as transaction:
    cursor = transaction.cursor()
    for key, value in cursor.iternext(True, True):
        print(key, value)
```
Both times gave me `test3` only.

### Describe What You Expected To Happen

I expected the call to iternext() to give me `test1` and iternext_dup() to give me `test2` and `test3`.

### Describe What Happened Instead

Both iternext() and iternext_dup() gave me `test3`.

**Comment by jnwatson** [comment]
You need to pass `dupdata=True` as a parameter to your `put` call.

**Comment by 25thbamofthetower** [comment]
> You need to pass `dupdata=True` as a parameter to your `put` call. Please see https://lmdb.readthedocs.io/en/release/#lmdb.Transaction.put

Isn't `dupdata=True` the default value? That's what I got from the docs and looking at the source code.

But I found out what was wrong. It seems dupsort doesn't work on the default database, and you need to create a new one via `open_db()`. E.g

```
env = lmdb.open(path, max_dbs=2)
db = env.open_db('db2', dupsort=True)  # doing just env.open_db(dupsort=True) doesn't work
...
```
Looking at the unit test for dupsort pointed me in this direction and it worked. Is it not suppose to work for the default database?

**Comment by jnwatson** [comment]
Sorry for the delay. I wish there were a better way to manage the flood of github notifications.

I misspoke. You must pass `overwrite=False`.

The persistence of flags of a database are somewhat tricky, and admittedly not documented well.

The flags (`dupsort`, `integerkey`, `reversekey`, `integerdup`, `dupfixed`) of a database are set when they are first created. Any flags provided to `open_db()` for an already-created database are ignored.

The state of the flags of the default database are all false, and there's no way to change the persistent state of the flags, so there's no way to do dupsort for the default database.
