### ISSUE TITLE
Unable to append duplicate values

### ISSUE THREAD

**Issue by jdsnape** [jnwatson/py-lmdb#235]
### Affected Operating Systems

* Linux

### Affected py-lmdb Version

0.98

### Describe Your Problem

I'm not sure if this a limitation of the underlying LMDB API, but I'm unable to use put or putmulti to append values when those value have duplicate keys. 

If I run:

```
creds = [
        (b'a', b'value1'),
        (b'b', b'value1'),
        (b'b', b'value2'),
        ]

db = env.open_db(b'test_db', dupsort=True)

with env.begin(write=True) as txn:
    c = txn.cursor(db=db)
    status = c.putmulti(creds, dupdata=True, overwrite=True)
    print(status)
```

I can then read all three cred values from the DB using next() and next_dup(). If I run the same code but with 

```
    status = c.putmulti(creds, dupdata=True, overwrite=True, append=True)

```
I can see it only inserts the first value for any duplicate key. This is the same for the put() method as well.

Am I missing something, or is this just a limitation I need to account for?

**Comment by jnwatson** [comment]
Sorry, this one took me a while to understand.

Congratulations, you have found a bug, and the bug is in py-lmdb and not downstream. The problem is that for tuples with duplicate keys, one must pass a separate flag called `MDB_APPENDDUP` (which you can't do currently from Python town).

Keep in mind that `append` is only an performance optimization. Removing that argument it will have no effect on the final database state.

Regardless, I'll fix it.

**Comment by jdsnape** [comment]
Thanks for confirming :) My use case is inserting lots (hundreds of millions) of keys. I've found that if I simply `put` the values then the time to insert each value gets longer and longer the more I insert (as expected). Hence I've presorted the data and am appending which finishes in a reasonable time. 

I hoping that `putmulti` would give a further optimisation over inserting the values one key at a time.

**Comment by jnwatson** [comment]
`putmulti` would indeed give an optimization by reducing the Python overhead. You can still use `putmulti`, but you can't use `append`.

Another mistake I've made is waiting for too many keys to commit. You should be committing every ~100K keys (depending on value size), depending on your available RAM. You're trying to avoid an extra round trip to disk from swapping when the change is pending.

**Comment by jdsnape** [comment]
Thanks!
