### ISSUE TITLE
segment fault

### ISSUE THREAD

**Issue by 15663671003** [jnwatson/py-lmdb#236]
When I start a write process and a read-only process, a segfault occurs in the write process. When I set the lock parameter of the read-only process to False, there is no segment fault. Why is this?

### Affected Operating Systems

* Linux

### Affected py-lmdb Version

    0.9.8

### py-lmdb Installation Method

    pip install lmdb

### Using bundled or distribution-provided LMDB library?

Bundled

### Distribution name and LMDB library version

Use "print lmdb.version()" from a Python prompt.

```

**Comment by jnwatson** [comment]
What is the filesystem the file is on? Do you have the stack trace?

Are these processes completely separate? Do you have any example code?

**Comment by jnwatson** [comment]
Closed to no response.
