### ISSUE TITLE
lmdb stores the data inefficiently?

### ISSUE THREAD

**Issue by tueboesen** [jnwatson/py-lmdb#241]
I'm looking for a data file structure that enables fast reading of random data samples for deep learning, and have been experimenting with lmdb today. However, one thing that seems surprising to me is how inefficiently it seems to store the data. 
I have an ASCII file that is around 120 GB with gene sequences. 
Now I would have expected to be able to fit this data in a lmdb database of roughly the same size or perhaps even a bit smaller since ASCII is a highly inefficient storing method.
However what I'm seeing seems, to suggest that I need around 350 GB to store this data in a lmdb file and I simply don't understand that.
Am I not utilizing some setting correctly, or what exactly am I doing wrong here?

```
 import time
import lmdb
import pyarrow as pa

def dumps_pyarrow(obj):
    """
    Serialize an object.

    Returns:
        Implementation-dependent bytes-like object
    """
    return pa.serialize(obj).to_buffer()

t0 = time.time()
filepath = './../../Uniparc/uniparc_active/uniparc_active.fasta'
output_file = './../data/out_lmdb.fasta'
write_freq = 100000

start_line = 2
nprot = 0

db = lmdb.open(output_file, map_size=1e9, readonly=False,
               meminit=False, map_async=True)
txn = db.begin(write=True)
with open(filepath) as fp:
   line = fp.readline()
   cnt = 1
   protein = ''
   while line:
       if cnt >= start_line:
           if line[0] == '>': #Old protein finished, new protein starting on next line
               txn.put(u'{}'.format(nprot).encode('ascii'), dumps_pyarrow((protein)))
               nprot += 1
               if nprot % write_freq == 0:
                   t1 = time.time()
                   print("comitting... nprot={} ,time={:2.2f}".format(nprot,t1-t0))
                   txn.commit()
                   txn = db.begin(write=True)
                   line_checkpoint = cnt
               protein = ''
           else:
               protein += line.strip()
       line = fp.readline()
       cnt += 1


txn.commit()
keys = [u'{}'.format(k).encode('ascii') for k in range(nprot + 1)]
with db.begin(write=True) as txn:
    txn.put(b'__keys__', dumps_pyarrow(keys))
    txn.put(b'__len__', dumps_pyarrow(len(keys)))

print("Flushing database ...")
db.sync()
db.close()

t2 = time.time()
print("All done, time taken {:2.2f}s".format(t2-t0))
```

**Comment by jnwatson** [comment]
Your implementation seems reasonable. You could certainly speed it up by using a more efficiently key encoding strategy and using append=True on your put, but that will only have a marginal impact on size.

The store isn't going to compress or make anything more efficient. In fact, there is a bit of overhead that LMDB has to do to index the data. Keep in mind the database has to store the keys and the values.

How are you measuring the file size? 'du' is most reliable mechanism.

**Comment by tueboesen** [comment]
> How are you measuring the file size? 'du' is most reliable mechanism.

I'm not sure what you mean by 'du'?

By file size I assume you mean the required lmdb database size to store the 120 GB ASCII file?
It actually turned out to be just slightly more than 350 GB to store all the data, since I initially tried with a 350 GB database and that turned out to be too small.

**Comment by jnwatson** [comment]
'du' is a command line utility on *nix machines.
