### ISSUE TITLE
Reading a large amount of data makes the buffer/cache run out of memory, resulting in the decrease of reading speed

### ISSUE THREAD

**Issue by toyow** [jnwatson/py-lmdb#249]
![image](https://user-images.githubusercontent.com/37426295/91408776-fe646a00-e876-11ea-82e9-51a6143283a7.png)
Is there  anyway to limit the  buffer/cache size？

**Comment by jnwatson** [comment]
You have the cause and effect backwards. LMDB is fast until the OS doesn't have any more memory to keep storage paged in. In a typical LMDB application, its memory usage is dominated by the memory map causing the OS to page in parts of the database. 

The OS itself decides what parts to keep in memory and which to page out to disk. In Linux, you can tune system-wide and per-cgroup how aggressive the kernel is at keeping files in system cache. They call that property "swappiness". System-wide swappiness is configured via `/proc/sys/vm/swappiness`. Information on configuring swappiness per cgroup is [here](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt).

**Comment by jnwatson** [comment]
Also see: https://unix.stackexchange.com/questions/253816/restrict-size-of-buffer-cache-in-linux. A common mechanism to limit an application like this (that uses cgroups under the hood) is to run your program inside a docker container.
