### ISSUE TITLE
dupfixed affecting append to go through in non-dupsort dbs

### ISSUE THREAD

**Issue by madarez** [jnwatson/py-lmdb#250]
### Affected Operating Systems

* MacOS

### Affected py-lmdb Version

1.0.0 & 0.98; Please note that I don't believe this is relevant to #242 as the following case fails for lmdb==0.98 as well.

### py-lmdb Installation Method

pip install lmdb

### Distribution name and LMDB library version

(0, 9, 24)

### Describe Your Problem

I have a db that does not use duplicate keys. When I run the following script the last two puts do not go through. However, when I remove `dupfixed=True` tag in the db definition, all of the puts go through.

```python
import tempfile
import lmdb
import struct
fp = tempfile.TemporaryDirectory()
env = lmdb.Environment(path=fp.name, max_dbs=3)
db = env.open_db(b'scratch', integerkey=True, integerdup=True, dupfixed=True) # here

def append(key, value):
  pack_item = lambda x: struct.pack('I', x)
  with env.begin(db=db, write=True) as txn:
    print(txn.id(), txn.stat(db))
    return txn.put(key=pack_item(key), value=pack_item(value), append=True, db=db)

append(7,77) # returns True
append(8,88) # returns False
append(9,99) # returns False
```

### Describe What You Expected To Happen

I expected the db to ignore the dup options as the db is not duplicate sort, similar to how whether integerdup is set or not doesn't affect the operation of the db as a non-dupsort db. It's as if passing dupfixed=True, enables and disables append flags.

I know it's not the way a user is expected to use the db, but I just thought I should report it as a minor bug.

**Comment by jnwatson** [comment]
In order to use "append=True" in a put, the new key must be after the last key. Because you're using the txn id encoded as *little endian*, this property is not maintained, hence the put fails.

**Comment by madarez** [comment]
@jnwatson , I tried all the permutations with the appending the key-value pairs above. In fact, much simpler experiment fails above:
```python3
import tempfile
import lmdb
import struct
fp = tempfile.TemporaryDirectory()
env = lmdb.Environment(path=fp.name, max_dbs=3)
db = env.open_db(b'scratch', integerkey=True, integerdup=True, dupfixed=True) # here

def append(key, value):
  pack_item = lambda x: struct.pack('I', x)
  with env.begin(db=db, write=True) as txn:
    print(txn.id(), txn.stat(db))
    return txn.put(key=pack_item(txn.id()), value=pack_item(value), append=True, db=db)

append(8,88) # returns True
append(7,77) # returns False
```
This seems to set an unpredictable order between 7 and 8 as integer keys.

I understand that when IntegerKey is False, the sorting is lexicographical. But I fail to identify how I can make my incremental integer keys to qualify for an appendable increasing key in their bytes representation. I see that the upstream LMDB docs indicate that,
> MDB_INTEGERKEY Keys are binary integers in native byte order, either unsigned int or size_t, and will be sorted as such. The keys must all be of the same size

I tried coming up with a reconstruction on how the orders are set up via `lambda x : bin(int(struct.pack('>I',x).hex(), 16))[2:]`. This passes one other test that I've been busy with, but it obviously can't explain comparisons like above and I haven't extensively tested it. So, I was just hoping that you'd provide me with an implementation pointer that I could track to get the IntegerKey orders right.

If the worst comes to the worst, I can move away from having integerKeys to regular one to avoid these ordering issues. Strangely though, when I remove the IntegerKey flag, anyway that I run the experiments above, they pass with not returning False puts.

**Comment by jnwatson** [comment]
All you need is ` pack_item = lambda x: x.to_bytes(4, 'big')`.

You cannot ever use append and insert things out of order. If you want to do that, don't use `append=True`. I don't understand how you expect to be able to add 7 after 8. Perhaps you misunderstand what `append` is for? It is simply an optimization that makes inserting faster if you know that your key is greater than all other keys. It is not for adding new values for an existing key.

**Comment by madarez** [comment]
Thank you for your quick reply, @jnwatson . I missed to acknowledge that I understood that setting the pack_item with the 'big' endian returns True. What I was trying to communicate is that **regardless of the order of the put-appends**, if the pack_item is:

1. x.to_bytes(4, '**little**'): the second put-append always returns **False**.
1. x.to_bytes(4, '**big**'): the second put-append always returns **True**.

I expected that the lexicographical order of the bytes objects of 7 and 8 should result in one of the two being larger and the other being smaller. Therefore, the sorted keys property shouldn't have been violated with one of the two runs above. Strangely, I'm seeing any order succeeds with 'big endian', but no order is valid for 'little endian'. I hope I'm not missing something trivial here, and, if so, I apologize in advance for it.

P.S.: Just to further clarify: I'm not really trying to append in the sense of extending the values of an existing key. <details><summary>Side Note Here:</summary>Although, I'm interested in using the append property on dupkeys later on. But I suppose that's not a problem as dupsort keys have their own subdb that they put values to, and I just need to get the <i>b'scratch'</i> db's key order right. But I understand that's a different discussion.
</details>

**Comment by jnwatson** [comment]
I see what you're talking about now. Thank you for your patience. I'm looking into it.

**Comment by jnwatson** [comment]
Yikes. There's good news and bad news. 

The good news is that a workaround/fix is easy: when you specify `dupfixed=True` on `open_db()`, always also specify `dupsort=True`. 

The bad news is that py-lmdb should do that for you, and that the underlying lmdb puts a null key in the database when you don't (which screws up lots of things, including append mode).

I'm going to leave this issue open until py-lmdb makes sure this doesn't happen.
