### ISSUE TITLE
Incorrect documentation for Environment.stat()

### ISSUE THREAD

**Issue by NightTsarina** [jnwatson/py-lmdb#254]
Hi,

The documentation says:
> Space usage can be monitored using Environment.stat():
>
>    \>>> pprint(env.stat())
>    {'branch_pages': 1040L,
>
>     'depth': 4L,
>     'entries': 3761848L,
>     'leaf_pages': 73658L,
>     'overflow_pages': 0L,
>     'psize': 4096L}
>
> This database contains 3,761,848 records and no values were spilled (overflow_pages).

But this is not correct when sub-dbs are in use, and only stats for the unnamed database are given. To see the total number of entries, you need to iterate over all databases and aggregate the statistics (and for this reason I opened #253 a few minutes ago)

**Comment by jnwatson** [comment]
Thank you for your observation. I have corrected the documentation.
