### ISSUE TITLE
Documentation Enhancement Suggestion for overwrite tag of transaction's put

### ISSUE THREAD

**Issue by madarez** [jnwatson/py-lmdb#259]
### Affected Operating Systems

* MacOS

### Affected py-lmdb Version

1.0.0

### py-lmdb Installation Method

pip install lmdb

### Distribution name and LMDB library version

(0, 9, 24)

### Describe Your Problem

Reading the documentation on [transaction's put](https://lmdb.readthedocs.io/en/latest/#lmdb.Transaction.put), for a db that is opened with dupsort=True and, two puts with the same key, say k:v1 and k:v2, I got the impression that the mapped value would change according to the following table:

|                               | overwrite=True | overwrite=False  |
| ----------------- |-----------------| -----------------|
| dupdata=True      | v1,v2  | v1 |
| dupdata=False     | v2      | v1 |

However, I'm getting the following behaviour:
|                               | overwrite=True | overwrite=False  |
| ----------------- |-----------------| -----------------|
| dupdata=True      | v1,v2  | v1 |
| dupdata=False     | v1,v2  | v1 |

```python
import tempfile
import lmdb
import struct

over=True
dup=False

fp = tempfile.TemporaryDirectory()
env = lmdb.Environment(path=fp.name, max_dbs=1)
db = env.open_db(b'scratch', dupsort=True)
pack_item = lambda x: x.to_bytes(4, 'big')

def append(key, value):
  with env.begin(db=db, write=True) as txn:
    print(txn.put(key=pack_item(key), value=pack_item(value), dupdata=dup, overwrite=over, db=db))
    print(txn.id(), txn.stat(db))

append(8,1)
append(8,2)

with env.begin(db=db, write=True) as txn:
  print(txn.id(), txn.stat(db)) # shows two stored entries
```

### Describe What You Expected To Happen

The ambiguous case is `overwrite=True and dupdata=False` in which I expected a `replace` behaviour to happen. This might be a subjective suggestion as one can argue that `replace` already exists on its own, and I sure wouldn't mind if the developers just decide to close this ticket without any resolution. However, I'd personally advocate for explicitly describing the behaviour of `overwrite=True and dupdata=False` under the `overwrite` tag of [transaction's put](https://lmdb.readthedocs.io/en/latest/#lmdb.Transaction.put) as a separate case.

**Comment by jnwatson** [comment]
Thank you for your detailed analysis. I think I've wrestled with this 3 or 4 times, and each time, it takes me some experimenting to remember how it works. This is odd behavior inherited from upstream `mdb_put` `MDB_NODUPDATA` flag. The only actual behavior it causes is, if `dupdata` is set to false, the method will return `False` if the key/val `combination` already exists.

I'm going to leave this open until I fix the documentation.
