### ISSUE TITLE
py-lmdb doesn't work with Python 3.10

### ISSUE THREAD

**Issue by jnwatson** [jnwatson/py-lmdb#261]
Just beating everyone to the punch.

Python 3.9 eliminated several long-deprecated C API functions, and some that weren't even deprecated, but that is partially my fault because I asked the Python maintainers pointed questions about them.

This is the point at which Python maintainers really really don't care about making it easy to maintain a C extension in 2.7 and latest Python. I don't blame them.

I do think this means that the days of py-lmdb continued support for Python 2 are numbered.

**Comment by encukou** [comment]
It seems that the removed API is `PyObject_AsReadBuffer`, right?

(Sorry if I'll now explain what's obvious; I don't remember seeing the pointed questions.)
`PyObject_AsReadBuffer` was replaced by `PyObject_GetBuffer`/`PyBuffer_Release`, which *are* available in Python 2.7.

The following (untested) patch should make py-lmdb compile with Python 3.10:
```patch
diff --git a/lmdb/cpython.c b/lmdb/cpython.c
index 32cd7ec..32deb23 100644
--- a/lmdb/cpython.c
+++ b/lmdb/cpython.c
@@ -588,9 +588,23 @@ val_from_buffer(MDB_val *val, PyObject *buf)
         type_error("Won't implicitly convert Unicode to bytes; use .encode()");
         return -1;
     }
+#if PY_VERSION_HEX < 0x03000000
     return PyObject_AsReadBuffer(buf,
         (const void **) &val->mv_data,
         (Py_ssize_t *) &val->mv_size);
+#else
+    // Emulation of the Python 2.x buffer protocol
+    Py_buffer pybuffer;
+    int result = PyObject_GetBuffer(buf, &pybuffer, PyBUF_SIMPLE);
+    if (result != 0) {
+        return -1;
+    }
+    val->mv_data = pybuffer.buf;
+    val->mv_size = pybuffer.len;
+    // Release buffer and hope the memory isn't freed while we use it
+    PyBuffer_Release(&pybuffer);
+    return 0;
+#endif
 }
 
 /* ------------------- */
```
If it looks unsafe, it is – yet this is almost exactly [what `PyObject_AsReadBuffer` did in Python 3](https://github.com/python/cpython/blob/8fe57aacc7bf9d9af84803b69dbb1d66597934c6/Objects/abstract.c#L311-L327), and what the 2.x buffer protocol was all about.

I'm all talk, unfortunately. I don't dare to fix py-lmdb properly: I don't know enough about how lmdb handles data to place the `PyBuffer_Release`s.

**Comment by AustEcon** [comment]
Any chance of getting wheels for python 3.10 anytime soon?

**Comment by claird** [comment]
[Me, too](https://github.com/jnwatson/py-lmdb/issues/261#issuecomment-980837500):  I want a **wheel** for Py3.10--although not enough to offer one myself.

_However_, if someone has clarity about what will be necessary to achieve a reliable **wheel**, and can describe the programming targets that will enable it, I'll certainly consider any required C or Python coding that helps.

**Comment by jnwatson** [comment]
Sorry, i’ bee been on a little hiatus while I got the legal issues to
committing to this worked out with my new employer. They are now resolved.

The main technical hurdle is that some formerly deprecated APIs in the
CPython C API are now gone.

There are new APIs, but they aren’t drop-in replacements, and they are in a
tricky part of the code.

I’ll get to it soon.

Nic

**Comment by shadchin** [comment]
JFYI: [Resurrect the old buffer protocol](https://github.com/python/cpython/pull/27437)

**Comment by jnwatson** [comment]
Just need to release.

**Comment by jnwatson** [comment]
Now released.
