### ISSUE TITLE
Can’t pickle environment object during multiprocessing

### ISSUE THREAD

**Issue by sofutofu** [jnwatson/py-lmdb#266]
### Describe Your Problem

I’m currently trying to run lmdb lookups in multiprocessing. I have 5 different lmdb mdb files, and each one takes roughly 2-8 seconds to look up 150k times. So all together it can add up if I run it sequentially. So I tried doing this with multiple processes using the python multiprocessing module, but it keeps giving me a cannot pickle the env object.

This seems to be a common thing, as I found a related issue for pytorch. Are there any suggestions on how to do this?

I’m running this in a Linux docket container on Mac OS X.

```python
import multiprocessing as mp

with mp.Pool(processes=4) as pool:
    for mdb_type in [...]:
        foo = Foo(). # this will open all mbd env files on init

        if mbd_type == ‘A’:
            results = pool.starmap(foo.lookup_A_mdb, [...])   # this will lookup db with dupsort = True
        elif ...

        # and so on
```

**Comment by jnwatson** [comment]
Either you need a different multiprocessing scheme or you need to open the lmdb files on the inside of the context manager.
