### ISSUE TITLE
Process crashes when I try to put new items.

### ISSUE THREAD

**Issue by samehraban** [jnwatson/py-lmdb#267]
### Affected Operating Systems

* Linux

### Affected py-lmdb Version

1.0.0

### py-lmdb Installation Method
 pip 

### Using bundled or distribution-provided LMDB library?

Bundled

### Distribution name and LMDB library version

0.9.24

### Machine "free -m" output

```
              total        used        free      shared  buff/cache   available
Mem:          32111       19793         534         285       11783       11581
Swap:         34526        1361       33165
```

### Describe Your Problem

I'm no longer able to put items into one of my lmdb storages. Whenever I try to put an item to it, it crashes.

### Errors/exceptions Encountered

```
build/lib/mdb.c:2127: Assertion 'rc == 0' failed in mdb_page_dirty()
Aborted (core dumped)

```

### Describe What You Expected To Happen
I expected proper exception being raised and maybe a way to recover this error.

### Describe What Happened Instead
The Python process crashed.

I understand that underlying abort is raised by lib lmdb but is there no way to handle it? Any idea what is wrong?

**Comment by jnwatson** [comment]
This looks like a database corruption. Try making a compact copy (`python -m lmdb copy --compact --env <oldpath> <newpath>`) of the failing database and trying the same with the new copy.

**Comment by samehraban** [comment]
@jnwatson Any idea what may went wrong?

**Comment by jnwatson** [comment]
Without having a stack trace and a debugger, it is hard to tell.

**Comment by samehraban** [comment]
When I tried to handle the abort signal with `signal` module of python, the registered signal handler never get called. Does it mean there is nothing we can do in python to handle this?

**Comment by jnwatson** [comment]
Correct.
