### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by dbermond** [jnwatson/py-lmdb#278]
### Affected Operating Systems

* Linux

### Affected py-lmdb Version

    1.1.1

### py-lmdb Installation Method

    Not applicable, since this is a build issue.

### Using bundled or distribution-provided LMDB library?

Distribution

### Distribution name and LMDB library version

Distribution name: Arch Linux
lmdb library: 0.9.28

### Machine "free -m" output

```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          15423        3076        8139        2207        4208        9810
Swap:          4095           0        4095
```

### Other important machine info

None

### Describe Your Problem

Test fails when building version 1.1.1.

I can confirm that tests were passing fine until version 1.1.0.

### Errors/exceptions Encountered

```
=================================== FAILURES ===================================
_______________________ CursorTest2.testIterWithDeletes ________________________

self = <cursor_test.CursorTest2 testMethod=testIterWithDeletes>

    def testIterWithDeletes(self):
        ''' A problem identified in LMDB 0.9.27 '''
        self.c.put(b'\x00\x01', b'hehe', dupdata=True)
        self.c.put(b'\x00\x02', b'haha', dupdata=True)
        self.c.set_key(b'\x00\x02')
        it = self.c.iternext()
        self.assertEqual((b'\x00\x02', b'haha'), next(it))
        self.txn.delete(b'\x00\x01', b'hehe', db=self.db)
>       self.assertRaises(StopIteration, next, it)
E       AssertionError: StopIteration not raised by next

tests/cursor_test.py:161: AssertionError
=========================== short test summary info ============================
FAILED tests/cursor_test.py::CursorTest2::testIterWithDeletes - AssertionErro...
======================== 1 failed, 185 passed in 1.17s =========================
```

### Describe What You Expected To Happen

I expected the tests to pass.

### Describe What Happened Instead

The tests fails to run.

### Additional System Information
- python: 3.9.1
- lmdb: 0.9.28
- pytest: 6.2.1

**Comment by jnwatson** [comment]
That was fast. This is a downstream bug in lmdb 0.9.27 and 0.9.28. See https://bugs.openldap.org/show_bug.cgi?id=9461.
