### ISSUE TITLE
cold LMDB read speed is slower than raw files over NFS

### ISSUE THREAD

**Issue by ajtao** [jnwatson/py-lmdb#281]
### Affected Operating Systems

* Linux

### Affected py-lmdb Version

1.0.0

### py-lmdb Installation Method

    pip install lmdb

### Using bundled or distribution-provided LMDB library?

Bundled

### Distribution name and LMDB library version

0,9,26

### Machine "free -m" output

free -m                                                                                                                                                                                                 total        used        free      shared  buff/cache   available
Mem:         515876        6282      486422           2       23172      506256
Swap:          1907           0        1906

### Other important machine info

Running docker on 18.04 kernel 5.4.0-58-generic

### Describe Your Problem

I'm using LMDB to hold ImageNet dataset jpegs.
So this is 1.2M images. The map size is 1099511627776 * 2.
I'm using pytorch with 8 worker threads per GPU and 8GPUs under a distributed data parallel training system, so 64 dataloader worker threads total in one system.

The problem is that if i compare training with LMDB to training with raw files, the first epoch (cold caches) of LMDB training is as much as 5x slower than raw files. The second epoch, after files have been brought into cacheFS appears to be comparable in speed.

I'm wondering if you have any clues as to why i might be seeing this. I am able to observe this on multiple runs, so i don't believe a fluke.

### Errors/exceptions Encountered

na

### Describe What You Expected To Happen

I expected the first epoch of training with LMDB to be no slower than the first epoch with raw files.

### Describe What Happened Instead

na

**Comment by ajtao** [comment]
The LMDB reading code is here: https://github.com/rmccorm4/PyTorch-LMDB/blob/master/folder2lmdb.py#L23-L66

**Comment by jnwatson** [comment]
Traditionally, NFS is very slow for databases. The protocol isn't well optimized for memory mapped files, and the filesystem cache interaction is poor.

**Comment by ajtao** [comment]
Hi @jnwatson I appreciate the feedback. Do you have any pointers to places i should dig to get better speed here? Alternative database formats or even filesystem solutions. Or are there tweaks to LMDB configuration that would lead to better behavior?

**Comment by jnwatson** [comment]
Just copying it to a local filesystem would significantly improve performance. You could also lock the file in memory with a tool like [vmtouch](https://linux.die.net/man/8/vmtouch) (e.g. vmtouch -l foo.lmdb) before you run your Python script.

**Comment by ajtao** [comment]
Appreciate it very much!
