### ISSUE TITLE
lmdb.InvalidParameterError: mdb_txn_begin: Invalid argument on Linux WSL1

### ISSUE THREAD

**Issue by espdev** [jnwatson/py-lmdb#283]
### Affected Operating Systems

* Linux (Ubuntu 20.04, WSL)

### Affected py-lmdb Version
```
1.1.1
```
### Python version
```
3.9
```

### py-lmdb Installation Method

Installed from PyPI:
```
pip install lmdb
```

### Using bundled or distribution-provided LMDB library?

Bundled

### Distribution name and LMDB library version

0.9.26

### Describe Your Problem

I'm getting the following error on Linux (WSL) when I'm trying to use lmbd in concurrent reading/writing from several processes:
```
lmdb.InvalidParameterError: mdb_txn_begin: Invalid argument
```

There is a minimal reproducible code example:
```python
import multiprocessing as mp
import lmdb

DB_FNAME = 'db'


def update_worker(queue):
    env = lmdb.open(DB_FNAME, subdir=False)

    while True:
        key = queue.get()
        if key is None:
            env.close()
            break

        print('updating key...')

        with env.begin(write=True) as tr:
            value = tr.get(key)
            if value:
                tr.replace(key, value + b'_spam')


def main():
    queue = mp.Queue()

    p = mp.Process(target=update_worker, args=(queue,))
    p.start()

    env = lmdb.open(DB_FNAME, subdir=False)

    with env.begin(write=True) as tr:
        tr.put(b'foo', b'bar')

    with env.begin() as tr:
        value = tr.get(b'foo')

    assert value == b'bar'

    queue.put(b'foo')
    queue.put(None)
    p.join()

    with env.begin() as tr:
        value = tr.get(b'foo')

    env.close()

    assert value == b'bar_spam'


if __name__ == '__main__':
    main()
```

The code works fine on Windows. On Linux I'm getting the following exception:
```
Traceback (most recent call last):
  File "check_lmbd.py", line 55, in <module>
    main()
  File "check_lmbd.py", line 46, in main
    with env.begin() as tr:
lmdb.InvalidParameterError: mdb_txn_begin: Invalid argument
```

Also this occurs in the cases like this:
```
process 1: open db
process 2: open db
process 2: make a read/write transaction
process 2: close db
process 1: make a read/write transaction and has failed
```

In this case process 1 opens db before process 2. In my case I have an application (process 1) that opens a database on start and keeps it open always. And some other processes sometimes open, write and close the database. After this the application fails during a read/write transaction.

Also if I open a database with `lock=False`, the error does not occur, but I would like to use lock mechanism out of the box.

Maybe I'm doing something wrong? However, the error looks incomprehensible anyway.

**Comment by jnwatson** [comment]
What version of WSL are you using? What filesystem are you using? In WSL version 1, I've heard of all sorts of weirdness in emulating filesystem locks. The error is likely caused by an unusual failure of a system call.

I can't repro your problem at all here on Ubuntu native 20.04. I tried adding sleeps in various places and running it a bunch.

The output of `strace -f -e trace=file python lmdbbug.py` might elucidate the failing system call.

**Comment by espdev** [comment]
@jnwatson 
I can confirm, the error occurs only in WSL. I just checked the code on native Ubuntu 20.04 - it works without any errors.
I use WSL2, filesystem:
```
$ df -Th
Filesystem     Type   Size  Used Avail Use% Mounted on
rootfs         lxfs   446G  353G   94G  80% /
none           tmpfs  446G  353G   94G  80% /dev
none           tmpfs  446G  353G   94G  80% /run
none           tmpfs  446G  353G   94G  80% /run/lock
none           tmpfs  446G  353G   94G  80% /run/shm
none           tmpfs  446G  353G   94G  80% /run/user
tmpfs          tmpfs  446G  353G   94G  80% /sys/fs/cgroup
C:\            drvfs  446G  353G   94G  80% /mnt/c
```

Trace:
```
strace -f -e trace=file -o lmdb_trace.txt python check_lmdb.py
```
[lmdb_trace.txt](https://github.com/jnwatson/py-lmdb/files/6230407/lmdb_trace.txt)

**Comment by jnwatson** [comment]
I don't see anything in the strace. Try tracing all the things: `strace -f python /tmp/lmdbbug.py`

I set up a WSL 2 environment. I tried using the same Python version, everything. I can't repro.

Does it run differently on tmpfs vs drvfs (Windows)?

**Comment by espdev** [comment]
The code works without errors on WSL2.

Filesystem info for WSL2:
```
df -Th
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/sda       ext4      251G   12G  227G   5% /
tmpfs          tmpfs     993M     0  993M   0% /mnt/wsl
tools          9p        446G  354G   93G  80% /init
none           devtmpfs  991M     0  991M   0% /dev
none           tmpfs     993M     0  993M   0% /run
none           tmpfs     993M     0  993M   0% /run/lock
none           tmpfs     993M     0  993M   0% /run/shm
none           tmpfs     993M     0  993M   0% /run/user
tmpfs          tmpfs     993M     0  993M   0% /sys/fs/cgroup
C:\            9p        446G  354G   93G  80% /mnt/c
```

I'm not sure if it makes sense to study the issue with WSL1 deeper and its "weirdness in emulating filesystem locks".

**Comment by jnwatson** [comment]
No, WSL1 is a known issue with lots of database-like things.

**Comment by george-GGG** [comment]
I have met this error too, but when I change the variable "env" to something else, like "env1", the error disappeared! I don't know why, would someone explain it?
