### ISSUE TITLE
lmdb.InvalidParameterError: mdb_txn_begin: Invalid argument

### ISSUE THREAD

**Issue by Mullich123** [jnwatson/py-lmdb#289]
### Affected Operating Systems
Linux
### Affected py-lmdb Version
'1.0.0'
### py-lmdb Installation Method
pip install lmdb
### Using bundled or distribution-provided LMDB library?
Bundled
### Distribution name and LMDB library version
(0, 9, 24)
### Machine "free -m" output
              total                used        free             shared  buff/cache   available
Mem:         255551       19222      231116         284         5212          234480
Swap:         16266        8394        7872
### Describe Your Problem

I am using horovod to do some distribution training on Linux.And by using MPI, I open 50 processes to load 
exactly the same data in the same path.And then the error below happened.Curiously,sometimes it runs normally,
sometimes it will raise the error.Could you explain this phenomenon for me?Thanks a lot.

### Errors/exceptions Encountered
  File "/public/home/user0/Tiger/test_horovod/prepareData.py", line 336, in Get_cursor
    env = lmdb.Environment(db_fn)
lmdb.InvalidParameterError: mdb_txn_begin: Invalid argument

**Comment by Mullich123** [comment]
what does 'It is a serious error to have open the same LMDB file in the same process at the same time.' mean in lmdb 1.0.0 documentation?

**Comment by Mullich123** [comment]
If main process have created an environment, how the other process use it instead of creating a new one?

**Comment by jnwatson** [comment]
LMDB will keep separate processes from overwriting over each other. However, it can't distinguish between requests from the same process from different environment objects. This will lead to data corruption.

Each process should open its own environment object (pointing at the same path).

**Comment by jnwatson** [comment]
Another thing to keep in mind that, normally, calling fork to create new processes will keep existing file handles open in the new process. It is best to create an environment after the processes have forked.

**Comment by Mullich123** [comment]
it's very useful,thanks a lot
