### ISSUE TITLE
Mac & win binary wheels missing from v1.2.0 pypi release

### ISSUE THREAD

**Issue by titusz** [jnwatson/py-lmdb#292]
Our updates to 1.2.0 failed. While v1.1.1 had binary wheels for linux, mac and win (https://pypi.org/project/lmdb/1.1.1/#files) the latest release has wheels only for linux (https://pypi.org/project/lmdb/#files). Not sure if that was intended?

**Comment by jnwatson** [comment]
It was not. I'll start looking into it ASAP.

**Comment by jnwatson** [comment]
I see the problem. I'll have to cut a new release. I'll have a 1.2.1 out by the end of today.

**Comment by jnwatson** [comment]
Problem fix. Pending new release.

**Comment by jnwatson** [comment]
1.2.1 is released. Thank you for your prompt reporting.
