### ISSUE TITLE
Possible to open a database by file handle?

### ISSUE THREAD

**Issue by pmeier** [jnwatson/py-lmdb#297]
Is it possible to open a database for reading if I have a open file handle to the data and lock files?

---

I'm working on a library that wraps common datasets to make them easier accessible. To save disk space we are looking into ways to access the data from within archives without extracting them. It is possible to iterate an archive and get an open file handle for each file within. 

One of our dataset comprises multiple archives with the following structure:

```
$ unzip bedroom_train_lmdb.zip
Archive:  bedroom_train_lmdb.zip
   creating: bedroom_train_lmdb/
  inflating: bedroom_train_lmdb/data.mdb  
  inflating: bedroom_train_lmdb/lock.mdb  
```

Given this setup, is it possible to read the data (writing is not needed) without extracting the archive? In the documentation I only found ways to open a database by path. This does not work here, since without extracting the path does not exist.

**Comment by jnwatson** [comment]
I'm afraid the upstream library py-lmdb uses doesn't have an API to open an environment file by file handle or descriptor.

If you're on Linux, you might explore fuse-zip (https://linux.die.net/man/1/fuse-zip). It would give you a file path inside a zip file without explicitly extracting it.

**Comment by pmeier** [comment]
Thanks for the clarification. From what I understand from `fuse-zip`, the archive is "mounted" in memory from where file access is possible. This is unfortunately not an option, since the datasets rarely fit into memory in the first place. Still, thanks for the suggestion.
