### ISSUE TITLE
[Question] What is the problem with the following code?

### ISSUE THREAD

**Issue by qiuwei** [jnwatson/py-lmdb#300]
### Affected Operating Systems

* Linux

### Affected py-lmdb Version
1.0.0
### py-lmdb Installation Method
pip install lmdb

### Using bundled or distribution-provided LMDB library?
Bundled

### Distribution name and LMDB library version
(0, 9, 24)

### Machine "free -m" output

e.g.

```
             total       used       free     shared    buffers     cached
Mem:         24154      23874        279         21        386       8175
-/+ buffers/cache:      15313       8840
Swap:            0          0          0
```

### Describe Your Problem

```
import lmdb


class Wrapper:
    def __init__(self):
        self.env = lmdb.open("/tmp/lmdb", map_size=1e6, readonly=False)

    def list_keys(self):
        result = []
        with self.env.begin() as txn:
            for key, value in txn.cursor():
                key = key.decode()
                result.append(key)
        return result

    def put(self, k, v):
        with self.env.begin(write=True) as txn:
            txn.put(k.encode(), v.encode())

if __name__ == "__main__":
    print(lmdb.__version__)
    print(lmdb.version())
    w1 = Wrapper()
    w1.put("a", "b")
    print(w1.list_keys()) # works

    w2 = Wrapper()
    print(w2.list_keys()) # works
    w2 = w1
    print(w1.list_keys()) # raises Exception
    print(w2.list_keys()) # raises Exception

```

### Errors/exceptions Encountered

Why would the above code raise `lmdb.BadRslotError: mdb_txn_begin: MDB_BAD_RSLOT: Invalid reuse of reader locktable slot` only afte the assignment `w2 = w1` ?

```
Traceback (most recent call last):
  File "/Users/wqiu/Projects/dzstore/examples/lmdb_bug.py", line 30, in <module>
    print(w1.list_keys())
  File "/Users/wqiu/Projects/dzstore/examples/lmdb_bug.py", line 10, in list_keys
    with self.env.begin() as txn:
lmdb.BadRslotError: mdb_txn_begin: MDB_BAD_RSLOT: Invalid reuse of reader locktable slot
```

### Describe What You Expected To Happen
I am not sure whether it is a bug or I have misused the API.

Could you explain a bit what is going on here? Thanks in advance!

**Comment by jnwatson** [comment]
You have two handles open to the same lmdb file in the same process. That's specifically disallowed.

From the docs:
"It is a serious error to have open the same LMDB file in the same process at the same time. Failure to heed this may lead to data corruption and interpreter crash."
