### ISSUE TITLE
build/lib/mdb.c:5940: Assertion 'IS_LEAF(mp)' failed in mdb_cursor_next()

### ISSUE THREAD

**Issue by Tasaddar12** [jnwatson/py-lmdb#306]
### Affected Operating Systems

* Linux

### Affected py-lmdb Version

    1.2.1

### py-lmdb Installation Method

pip3 install lmdb

### Using bundled or distribution-provided LMDB library?

Bundled

### Distribution name and LMDB library version

(0, 9, 29)

### Machine "free -m" output

```
sudo free -m
              total        used        free      shared  buff/cache   available
Mem:          15722        3950        5749         125        6023       11352
Swap:          2047         219        1828
```

### Other important machine info

Running in a docker container for a web application

### Describe Your Problem

I made no changes to my code or application and now it is crashing with this strange error.

### Errors/exceptions Encountered

```
docker-compose up web
Starting neso_web_1 ... 
Starting neso_web_1 ... done
Attaching to neso_web_1
web_1  |  * Serving Flask app "app" (lazy loading)
web_1  |  * Environment: development
web_1  |  * Debug mode: on
web_1  |  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
web_1  |  * Restarting with stat
web_1  |  * Debugger is active!
web_1  |  * Debugger PIN: 231-014-810
web_1  | build/lib/mdb.c:5940: Assertion 'IS_LEAF(mp)' failed in mdb_cursor_next()
neso_web_1 exited with code 250
```

### Describe What You Expected To Happen

For the code to run normally since nothing changed

### Describe What Happened Instead

I got an error and it crashed.

**Comment by jnwatson** [comment]
That looks like your DB file was corrupted.

**Comment by Tasaddar12** [comment]
How can that happen? What would cause that but then fix itself for no reason?

**Comment by jnwatson** [comment]
Does the database file live outside the docker container? The only situation I've seen is when you have a process sharing the same database file inside and outside the docker container.
