### ISSUE TITLE
Get invalid argument for mdb_txn_begin during multiprocessing

### ISSUE THREAD

**Issue by strawberryboba123** [jnwatson/py-lmdb#309]
I seem to get these invalid argument errors when I do multiprocessing and opening up the LMDB file in each process. It happens occasionally.

`lmdb.InvalidParameterError: mdb_txn_begin: Invalid argument`

### Affected Operating Systems
* Linux

### Affected py-lmdb Version
* 1.2.1

### py-lmdb Installation Method
* pipenv in docker container

### Describe Your Problem

I seem to get these invalid argument errors when I do multiprocessing and opening up the LMDB file in each process. It happens occasionally.

`lmdb.InvalidParameterError: mdb_txn_begin: Invalid argument`

```python
class LMDBConnection:
    class _context:
        def __init__(self, env, db):
            self.db = db
            self.env = env

        def __enter__(self):
            self.session = self.env.begin(self.db)
            return self.session

        def __exit__(self, exc_type, exc_val, exc_traceback):
            self.env.close()

    def begin(self, **kwargs):
        try:
            env = lmdb.open(path=dbpath, create=create, readonly=readonly, max_dbs=2)
        except Exception:
            ...

        try:
            db = env.open_db(key=dbname.encode('utf-8'), create=create, dupsort=True)
            return self._context(env, db)
        except Exception:
            ...
```
Then this is used like so:

```python
my_lmdb = LMDBConnection(...)
with my_lmdb.begin(dbname=dbname) as txn:
    cursor = txn.cursor()
    ...
```
The `lmdb.InvalidParameterError: mdb_txn_begin: Invalid argument` error always seems to occur at either `self.session = self.env.begin(self.db)` or `env = lmdb.open(path=dbpath, create=create, readonly=readonly, max_dbs=2)`.

But when I debug and print out the argument values, they're correct, as in they're the same as when the errors do not occur.

Any thoughts? Perhaps my implementation is not good?

**Comment by jnwatson** [comment]
Forking and using open LMDB handles can cause these problems. Either make sure you have no open handles when a fork happens, or use the non-forking context of multiprocessing.
