### ISSUE TITLE
lmdb.MapFullError: mdb_txn_commit: MDB_MAP_FULL: Environment mapsize limit reached

### ISSUE THREAD

**Issue by zyh3826** [jnwatson/py-lmdb#318]
### Affected Operating Systems

* Linux

### Affected py-lmdb Version

    1.0.0

### Other important machine info

under container

### Describe Your Problem

when i use txn.put, txn.delete, txn.get or even txn.commit this error happen, and I check other issues, always say increase map_size, but at the begin of create the database I set the value to 1Tb, when the error happened, the database only 736kb, how can I solve this problem, thanks a lot

### Errors/exceptions Encountered

```
Traceback (most recent call last):
  File "ut.py", line 354, in <module>
    fire.Fire()
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "ut.py", line 151, in test_media_asset_engine
    media_asset_engine.save()
  File "/source/code/zhaoyhy/AI_server/MediaAssetSearchLMDB/media_asset_search.py", line 648, in save
    self.fetch_class.save_to_db()
  File "/source/code/zhaoyhy/AI_server/MediaAssetSearchLMDB/rank_base.py", line 282, in save_to_db
    self.close_lmdb(self.movie_collection, self.movie_env)
  File "/source/code/zhaoyhy/AI_server/MediaAssetSearchLMDB/rank_base.py", line 125, in close_lmdb
    txn.commit()
lmdb.MapFullError: mdb_txn_commit: MDB_MAP_FULL: Environment mapsize limit reached
```

**Comment by jnwatson** [comment]
This sounds familiar. What's probably happening is a rarer failure is occurring. It might be having trouble writing out the file. You might be able to tell what the error is by running 'strace -e trace=file <regular python command that runs your script>'. That will output the result code from every file-based system call.

**Comment by zyh3826** [comment]
> This sounds familiar. What's probably happening is a rarer failure is occurring. It might be having trouble writing out the file. You might be able to tell what the error is by running 'strace -e trace=file '. That will output the result code from every file-based system call.

Thanks I will try this. I have another question, everytime I use txn.put(somthing new), unless I use txn.commit, the somthing new won't wirte to the file system, am I right? Thanks

**Comment by jnwatson** [comment]
That is correct. The alternative is you can use a context manager so you don't forget to commit. When it leaves the scope, the transaction will automatically be committed.
```
with env.begin(write=true) as txn: 
    txn.put(b'a', b'b')
    ...

```

**Comment by zyh3826** [comment]
> That is correct. The alternative is you can use a context manager so you don't forget to commit. When it leaves the scope, the transaction will automatically be committed.
> 
> ```
> with env.begin(write=true) as txn: 
>     txn.put(b'a', b'b')
>     ...
> ```

I use this way, and no error occured, thank you very much. I have another question, does lmdb support sub-database's sub-database, for example I have a sub-database movie, and I want to creat a sub-database action movie of this sub-database, how can I do? I find no answer in doc, do I miss something?

**Comment by jnwatson** [comment]
No, there's no built-in sub-databases of sub-databases. You can always pretend though, by, for example, appending the database names. That's pretty much how "directories" work in AWS S3.

**Comment by zyh3826** [comment]
> No, there's no built-in sub-databases of sub-databases. You can always pretend though, by, for example, appending the database names. That's pretty much how "directories" work in AWS S3.

Got it, thanks

**Comment by zyh3826** [comment]
Hi, is there has any method can iterate all sub-databases without give it's name or any method can get all sub-database names, can not find in doc, thanks a lot
