### ISSUE TITLE
Mysterious slow down in IO when sequentially loading lmdb to memory 

### ISSUE THREAD

**Issue by ray38** [jnwatson/py-lmdb#320]
### Affected Operating Systems

* Linux

### py-lmdb Installation Method

sudo pip install lmdb

### Distribution name and LMDB library version

1.0.0

### Machine "free -m" output

```
              total        used        free      shared  buff/cache   available
Mem:          64352        1245       49311           3       13795       62388
Swap:         62498        3631       58867
```
### Other important machine info

Same Issue happens for all Ubuntu machines

### Describe Your Problem

I'm using M2 nvme SSD for fast IO, and hdparm test did confirm that the cached read speed is ~17 GB/s and buffered disk read speed is ~1.6 GB/s.

I tried to load a series of lmdb files (~10G each) into memory for model training, the read speed (of the first file) starts out at ~1.5GB/s, but suddenly dropped to ~300M/s after the first ~15GB data was loaded, and that speed maintained low for the rest of the task (including loading of later files). I have enough memory, and the same slow down happens even if we just access the data and don't write the data into memory, so it shouldn't be related to memory I think.

I then tried to monitor using iotop, it seems as if the loading speed dropped at the precise moment when iotop detects and lists the task. The fact that once the slow down appears, the IO speed kept low for all the following files (regardless of order) is even more puzzling. I'm suspecting it's either the system that's limiting the IO speed, or the lmdb package has a bug.

here is part of the code I used to generate data:

```
    db = lmdb.open(
        lmdb_path,
        map_size=1099511627776 * 2,
        subdir=False,
        meminit=False,
        map_async=True,
    )
    ....

    idx = 0
    for do in tqdm(data_list, desc="Writing images to LMDB"):
        txn = db.begin(write=True)
        txn.put(f"{idx}".encode("ascii"), pickle.dumps(do, protocol=-1))
        txn.commit()
        idx += 1

    txn = db.begin(write=True)
    txn.put("length".encode("ascii"), pickle.dumps(idx, protocol=-1))
    txn.commit()

```

Then I load the data this way (a series of lmdb files)
```
    def connect_db(self, lmdb_path):
        env = lmdb.open(
            lmdb_path,
            subdir=False,
            readonly=True,
            lock=False,
            readahead=False,
            meminit=False,
            max_readers=1,
        )
        
        envs = []
        keys_list = []
        length_list = []
        for db_path in db_paths: # paths to the lmdb files
            temp_env = connect_db(db_path)
            envs.append(temp_env)
            keys_list.append(
                [f"{j}".encode("ascii") for j in range(temp_env.stat()["entries"])]
            )
            temp_length = pickle.loads(txn.get("length".encode("ascii")))
            length_list.append(temp_length)

        data_list = []
        for i, env in enumerate(envs):
            with envs[i].begin(write=False) as txn:
                for idx in tqdm(
                    range(length_list[i]),
                    desc="loading from {}".format(db_paths[i]),
                    total=length_list[i],
                    unit=" images",
                ):
                    data = txn.get(keys_list[i][idx])
                    data_object = pickle.loads(data) # comment out this line doesn't help
                    data_list.append(data_object)

```

### Describe What You Expected To Happen

During loading of the lmdb files, the speed should be consistently high at ~1.7G/s

### Describe What Happened Instead

the IO speed dropped to 300M/s after a while, and stayed there for the loading of current and all following lmdb files.

**Comment by jnwatson** [comment]
Multiple things are going on here: the data is stored in a B-Tree, so there are multiple nodes that must be hit for every new node read. Multiple caches exist to elide reading from disk, but one of those is filling up or being evicted too hastily.

This isn't really a LMDB thing, but an OS thing. I'd make sure that the mapped-in-memory is increasing as expected. You might try locking the target lmdb files into the buffer cache (try https://hoytech.com/vmtouch/) and see if that makes a performance difference.

**Comment by ray38** [comment]
@jnwatson Thank you very much for your insight! tbh I don't quite understand the issue here, but I'll definitely do some research as well as the memory test and update the results here.
meanwhile, based on your insight, it seems this slowdown behavior is actually expected? and probably generally happens to all applications that loads the data into memory? If that's the case -
 1) Is there any way to circumvent this issue? Maybe decrease the map size/ size of each lmdb file? Or maybe change the way I store data (using pickle)?
 2) Do you know if this is a ubuntu thing, or would this generally happen to other OS as well?
 3) If there is no obvious way to fix it with lmdb, are there other similar packages I could try instead (like h5py)?

Thank you again very much for your help!

**Comment by jnwatson** [comment]
Your main problem is that you're loading more stuff into RAM than you have RAM. This isn't a Ubuntu thing. You should definitely only have 1 env file open at a time to conserve RAM, and delete the data once you are done with it.
