### ISSUE TITLE
building 'cpython' extension   error: CCompiler.compile: Chaquopy cannot compile native code

### ISSUE THREAD

**Issue by egemenakbal** [jnwatson/py-lmdb#322]
cwd: /private/var/folders/66/t9mg3jhn7k5cfq28w9nbdmgm0000gn/T/pip-install-c5t5g4lk/lmdb/
  Complete output (17 lines):
  py-lmdb: Using bundled liblmdb with py-lmdb patches; override with LMDB_FORCE_SYSTEM=1 or LMDB_PURE=1.
  patching file lmdb.h
  patching file mdb.c
  py-lmdb: Using CPython extension; override with LMDB_FORCE_CFFI=1.
  running bdist_wheel
  running build
  running build_py
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/lmdb
  copying lmdb/cffi.py -> build/lib.macosx-10.9-x86_64-3.8/lmdb
  copying lmdb/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/lmdb
  copying lmdb/_config.py -> build/lib.macosx-10.9-x86_64-3.8/lmdb
  copying lmdb/tool.py -> build/lib.macosx-10.9-x86_64-3.8/lmdb
  copying lmdb/__main__.py -> build/lib.macosx-10.9-x86_64-3.8/lmdb
  running build_ext
  building 'cpython' extension
  error: CCompiler.compile: Chaquopy cannot compile native code

**Comment by jnwatson** [comment]
Chaquopy isn't going to work with the C python extension. You might try building with LMDB_FORCE_CFFI=1 to use the cffi version and see if that works.
