### ISSUE TITLE
last() returns 16777215th item instead of last item

### ISSUE THREAD

**Issue by qwertyforce** [jnwatson/py-lmdb#324]
Affected Operating Systems

    Linux
### Affected py-lmdb Version

    0.99
    1.30

### py-lmdb Installation Method

    sudo pip install lmdb

### Describe Your Problem
```python
import lmdb
DB_test = lmdb.open('./test.lmdb',map_size=1* 1000 * 1_000_000) #1gb

def int_to_bytes(x: int) -> bytes:
    return x.to_bytes((x.bit_length() + 7) // 8, 'big')

def int_from_bytes(xbytes: bytes) -> int:
    return int.from_bytes(xbytes, 'big')

data = [(int_to_bytes(x+1),int_to_bytes(x+1)) for x in range(20_000_000)]

with DB_test.begin(write=True) as txn:
    with txn.cursor() as curs:
        curs.putmulti(data)

with DB_test.begin(buffers=True) as txn:
    with txn.cursor() as curs:
        curs.last()
        x = curs.item()
        print(int_from_bytes(x[0])) # prints 16777215
        print(int_from_bytes(x[1])) # prints 16777215

max_int_key = -1
max_int_val = -1
with DB_test.begin(buffers=True) as txn:
    with txn.cursor() as curs:
        for data in tqdm(curs.iternext(keys=True, values=True)):
             max_int_key = max(max_int_key,int_from_bytes(data[0]))
             max_int_val = max(max_int_val,int_from_bytes(data[1]))
print(max_int_key) # prints 20000000
print(max_int_val)  # prints 20000000
```

**Comment by jnwatson** [comment]
Keys are stored in the order where the first byte is compared and then the next byte is compared. This means that 16777215 (0xffffff) will be stored after 20000000 (0x1312d00) because ff is greater than 13. If you change line 5 to `return x.to_bytes(4, 'big')` it will work as you expect because 0x00ffffff is now less than 0x01312d00.

**Comment by qwertyforce** [comment]
> Keys are stored in the order where the first byte is compared and then the next byte is compared. This means that 16777215 (0xffffff) will be stored after 20000000 (0x1312d00) because ff is greater than 13. If you change line 5 to `return x.to_bytes(4, 'big')` it will work as you expect because 0x00ffffff is now less than 0x01312d00.

Thank you for your help!
