### ISSUE TITLE
Building a Windows C-Extension 

### ISSUE THREAD

**Issue by dineshbvadhia** [jnwatson/py-lmdb#327]
I'm building a Windows C-Extension using code from a working C-Extension on linux.  Running a setuptools setup.py results in a cannot find `'lmdb.h'` and` 'lmdb.lib'`. 

Windows 10, Python 3.10.6, Visual C/C++ 2017 + BuildTools
```
from setuptools import Extension, setup
import numpy as np

setup(
    ext_modules = [
        Extension(
            name = "c_ext",
            include_dirs = ["src", np.get_include()],
            libraries = ["lmdb", "msvcrt", "advapi32"],
            sources = ["src/cext.c", "src/cext_db.c", etc.],),])

> python setup.py build_ext --inplace
...
LINK : fatal error LNK1181: cannot open input file 'lmdb.lib'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
```
i. Copied lmdb.h from the repo which solved this one but seems odd to do so.
ii Haven't solved the "cannot open 'lmdb.lib' " error and is baffling :(

**Comment by jnwatson** [comment]
It might be helpful to look at how the CI system does it: https://github.com/jnwatson/py-lmdb/blob/master/.github/workflows/python-package.yml#L92. I don't know why you're setting up your own build system. There's already a setup.py.

**Comment by dineshbvadhia** [comment]
Many apologies. Didn't see this. Thank-you
