### ISSUE TITLE
How to calculate map size?

### ISSUE THREAD

**Issue by abhijeetdhakane** [jnwatson/py-lmdb#331]
I am wondering if I have a dataset of size 200 GB, divided into 11 files. How do I calculate map size, for creating a LMDB database? Also, is it possible to concatenate the LMDB datasets. If I created 11 LMDB databases from 11 files? (how)

**Comment by jnwatson** [comment]
I'd start at triple your data size. There's a great deal of storage overhead.

You can always merge datasets by reading from one database and writing to another database, iterating through all the databases and keys.
