### ISSUE TITLE
Random crahes in multiprocess when opening the environment.

### ISSUE THREAD

**Issue by TheTioz** [jnwatson/py-lmdb#340]
Hello,

I am using py-lmdb and multiprocessing in pytorch on linux. It works very well when using version 1.0.0 but randomly crash on higher version.

I am unsure how lmdb environment should be open in multiprocessing context. Currently. I have multiple processes. Each time they need to read a batch of data from the db, they create an environment read many entries and close the environment. As suggested in [this issue](https://github.com/jnwatson/py-lmdb/issues/159):

> You could investigate using the multiprocessing module directly, or perhaps
> simply reopen the database prior to each lookup (although this will come
> with quite a performance penalty).

I should be able to work around the issue by opening the environment at the start of each process (like recommended in the issue cited before) and keeping it open, but it seems something like a race condition is happening in version higher than 1.0.0.

I made a very simplified version reproducing the problem. The following code seems to works on version 1.0.0 of lmdb but randomly fail when creating the environment on newer version with a: "lmdb.InvalidParameterError: mdb_txn_begin: Invalid argument"

```
import lmdb as lmdb
import concurrent.futures as cf

DB_PATH = "/tmp/db_test"

def f(value):
    e = lmdb.Environment(DB_PATH)
    with e.begin(write=False) as txn:
        out = int.from_bytes(txn.get(value.to_bytes(4, 'big')), 'big')
    e.close()
    return out

def create_db():
    n_entry = 10_000
    MB = 1024 * 1024
    dbpath = DB_PATH
    e = lmdb.Environment(dbpath, writemap=True, create=True, map_size=10 * MB)
    with e.begin(write=True) as txn:
        for i in range(n_entry):
            txn.put(i.to_bytes(4,"big"), i.to_bytes(10,"big"))


if __name__ == '__main__':
    create_db()
    print(lmdb.__version__)
    # adding this line prevent crash in 1.1.1 and above work without in 1.0.0
    #prevent_crash = lmdb.Environment(DB_PATH)

    with cf.ProcessPoolExecutor(max_workers=4) as executor:
        fs = [executor.submit(f, value) for value in range(10_000)]
        for future in cf.as_completed(fs):
            print(future.result())

```
Randomly opening an environment in the main process (see commented line) seems to prevent crashes (which confuse me even more).

Thank you very much for the help,
Best

**Comment by jnwatson** [comment]
This is a function of the multiprocess locks that lmdb uses to make sure that different processes don't stomp on each other. These locks aren't fork friendly which are what multiprocess uses. If you make sure that the processes exist before you open the first lmdb, and the processes never exit, then you should be safe.
