### ISSUE TITLE
Written data in the database contains weird character sequences.

### ISSUE THREAD

**Issue by gitb0y** [jnwatson/py-lmdb#343]
Edit this issue template as appropriate. If none of it seems relevant to your
issue, then you may delete the entire template, however, I may not respond to
issues that do not include important information that is mentioned in this
template!

### Affected Operating Systems

* Linux

### Affected py-lmdb Version

>>> print(lmdb.__version__)
1.4.1

### py-lmdb Installation Method

sudo python3 -m pip install lmdb

### Using bundled or distribution-provided LMDB library?

bundled

### Distribution name and LMDB library version

>>> print(lmdb.version())
(0, 9, 29)

### Machine "free -m" output

               total        used        free      shared  buff/cache   available
Mem:           64218         647         648           1       62923       62855
Swap:           8191           3        8188

### Other important machine info

5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Describe Your Problem

Wrote a script that splits 1 year into 2-minute date ranges, some entries get written in the database contain weird character sequences:

Here's a portion of json data retrieved from the database. E.g., those \xb's, \xd, \xba. 

"2022-08-03T12:40:00.023900+000
0":"2022-08-03T12:42:00.023900+0000","2022-08-03T14:42:00.\xb023961+0\xb000":"2022-08-03\xd414:44:02.023961+0000","0022-08-03T14:30:00.023955+0000"\xba"2022-08-03T14:32:00.023955+0000",

### Errors/exceptions Encountered

Because of those weird characters, json.loads fails and python scripts halts.

### Describe What You Expected To Happen

The written data should be free from any of those weird characters. These are program-generated data and not from external sources so we can rule out error in the source data, although when receiving data from external sources, I also encountered these random errors in the saved data (i.e., they also contain those weird characters.). I initially thought that those were the exact data i received from the external source but when i read the database and retrieve the program generated data (those date ranges split), i also found them to be erroneous.

**Comment by vEpiphyte** [comment]
@gitb0y Do you have any code you can share that reproduces this issue? A minimal reproduction case would help.
