### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by muslll** [jnwatson/py-lmdb#360]
Hi. Can the main dev or contributors please give an update on the maintainence status of this project?
I'm asking because I use it on one of my machine learning projects, and recently I've switched to python 3.12, which doesn't seem to be supported (as also [reported by others](https://github.com/jnwatson/py-lmdb/issues/355)). The lmdb version also seems to be outdated, according to [this issue](https://github.com/jnwatson/py-lmdb/issues/353). So it made me wonder the current status of this project and if the main devs are willing to keep maintaining it.
Thanks in advance.

**Comment by jnwatson** [comment]
I took a break. I'm back. Working through the backlog.
