### ISSUE TITLE
make_trans() failure paths

### ISSUE THREAD

**Issue by dw** [jnwatson/py-lmdb#67]
PyObject_New() does not initialize memory, meaning PyObject_Del() will indirectly invoke trans_clear which will attempt to free random pointers.

Also,

If mdb_txn_renew() fails then PyObject_Del() is called, except mdb_txn_abort() was not called

**Comment by astronouth7303** [comment]
Is this fixed now?

**Comment by dw** [comment]
It isn't broken in the sense that no bug has been reported, but the bug was filed because I haven't manually audited the constructor and destructor to make sure they can't ever possibly explode :)  It's basically a TODO comment in ticket form, so I'd prefer to keep it open
