### ISSUE TITLE
Support MDB_INTEGERKEY, MDB_INTEGERDUP and MDB_DUPFIXED

### ISSUE THREAD

**Issue by dw** [jnwatson/py-lmdb#81]
Per @heyman's measurements, there are significant storage benefits to using LMDB's integer modes. This bug is to decide on the approach for implementing them in the binding.

The options seem to be:
- Simple flag, user is responsible for all coding. Per @heyman's measurements there didn't seem to be much discernible impact on lookup performance from enabling the integer modes, so maybe this is the simplest and easily implemented approach.
- Push encoding into the binding itself. This was the original idea I had for implementing it. It would notably complicate the implementation, but the result would potentially be more pleasing.

As a common-denominator wrapper around a key-value store, one of many, I'm drawn toward option 1, but my perfectionist side is tempted to go with option 2.

Option 1 is also more flexible: if the user is receiving a pre-encoded int, there is no reason to decode it just so the binding can re-encode it.

Potential next steps: profile how much struct.packs & suchlike costs, or apply @heyman's patch as-is.

**Comment by pspacek** [comment]
Hello,

I've spent some time playing with `integerkey=True` databases with python-lmdb 4651bb3a865c77008ac261443899fe25f88173f2 and I have to say that manual encoding of integers to keys in my Python code proved to be error prone.

Based on this experience I propose to do encoding in the binding. I would be more than happy to read patches and test them if you want.

Regards,
Petr Špaček

**Comment by jnwatson** [comment]
This work has been completed.
