### ISSUE TITLE
Add CI tests for every build type.

### ISSUE THREAD

**Issue by dw** [jnwatson/py-lmdb#92]
Managed to break `LMDB_FORCE_SYSTEM` in the fix for 772767fcf95419ca5ff2d97f122126cb7b68decf, spotted by Jos in #88.

Ensure Travis CI config tries every build type before returning success

**Comment by astronouth7303** [comment]
What does "build type" refer to?

**Comment by jnwatson** [comment]
We've made some solid progress here with the latest CI. The only part missing is testing the bundled library.

**Comment by jnwatson** [comment]
The bundled option is now tested in CI. Resolved in https://github.com/jnwatson/py-lmdb/pull/282.

**Comment by dw** [comment]
Amazing job Nic!
